---
title: "`widgetframe` in Xaringan"
author: "Bhaskar Karambelkar"
date: "2017/01/13"
output:
  xaringan::moon_reader:
    chakra: libs/remark-latest.min.js
    css: ["default", "style.css"]
    nature:
      ratio: '16:9'
      highlightStyle: github
      countIncrementalSlides: false
      navigation:
        scroll: false
        click: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# `widgfetframe` in Xaringan

This is just a small demo of using `widgetframe` package to wrap `htmlwidgets` inside a `xaringan` presentation in responsive iframes.

---

# Leaflet

```{r leaflet-01}
library(leaflet)
suppressPackageStartupMessages(library(widgetframe))
l <- leaflet() %>% addTiles() %>% setView(0,0,2)
frameWidget(l, height = '300')
```

---

# Dygraph

```{r dygraph-01}
library(dygraphs)
ts <- dygraph(nhtemp, main = "New Haven Temperatures")
frameWidget(ts, height = 300, width = '95%')
```

---

# DT

```{r dt-01}
library(DT)
dt <-  datatable(
  head(iris, 20), 
  options = list(
     columnDefs = list(list(className = 'dt-center', targets = 5)),
     pageLength = 5, lengthMenu = c(5, 10, 15, 20)),
  fillContainer = T)

frameWidget(dt, height = 350, width = '95%')
```

